name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-typecheck:
    name: Lint, Type-Check, and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Linter
      - name: Run ESLint
        run: npm run lint
        env:
          CI: true

      # Step 5: Type-Check with TypeScript
      - name: Run TypeScript type-checking
        run: npm run type-check

      # Step 6: Run Tests
      - name: Run tests
        run: npm test
